title: Reopening RI
description: Rhode Island's chart toward reopening our economy in a phased approach.

repository: civic-imagination/summit-website.git
github.pages_hostname: https://civicfutures.io

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

baseurl: /
port: 4060
url: //civicfutures.io
twitter_handle: civicimagination


# Define some defaults
defaults:
  -
    values:
      layout: "page"
      author: "Reopening RI"


# Permalink Configuration
permalink: /blog/:year/:month/:title

# Post types
collections:
  team:
    output: true
    permalink: /awards/2019/:name
  events:
    output: false
    permalink: /events/:name

# Exclude from _site build
exclude: ['.git',
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'CNAME',
  'LICENSE',
  'feed.xml',
  'awards/README.md'
  ]


# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass


# Plugins and extras
plugins:
- jekyll-autoprefixer
- jekyll-github-metadata
